<a href="https://colab.research.google.com/github/SPraveeen/python_numpy_learning/blob/main/Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1,2,3,4,5]

In [ ]:
b = [1,2,3, "shivank"]

In [ ]:
type(b)

list

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
res = [i**2 for i in a]

In [ ]:
res

[1, 4, 9, 16, 25]

In [ ]:
import numpy as np

In [ ]:
int("2")

2

In [ ]:
b = np.array(a)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = b**2

In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
c

array([ 1,  4,  9, 16, 25])

In [ ]:
l = range(1000000)

In [ ]:
%timeit [i**2 for i in l]

501 ms ± 133 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
m = np.array(l)

In [ ]:
%timeit m ** 2

1.14 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
m.ndim

1

In [ ]:
m.shape

(1000000,)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(4, 3)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
list(range(1,5,2))

[1, 3]

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5,2)

array([1, 3])

In [ ]:
c = np.arange(1,5,0.5)

In [ ]:
type(c)

numpy.ndarray

In [ ]:
import numpy as np

arr = np.arange(5)


In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr[2:4] = 0

print(arr)

[0 1 0 0 4]


In [ ]:
np.array([1,2,3,1.0])

array([1., 2., 3., 1.])

In [ ]:
np.array([1,2,3,"shivank"])

array(['1', '2', '3', 'shivank'], dtype='<U21')

In [ ]:
np.array([100,'a',3000])

array(['100', 'a', '3000'], dtype='<U21')

In [ ]:
[100,'a',3000]

[100, 'a', 3000]

In [ ]:
np.array([1,2,3,1.0], dtype = "int")

array([1, 2, 3, 1])

In [ ]:
np.array(["shivank", "ajay"], dtype = "int")

ValueError: ignored

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.astype('float')

array([1., 2., 3., 4.])

In [ ]:
a = np.arange(10,22)

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [ ]:
a[-1]

21

In [ ]:
a[[0,2]]

array([10, 12])

In [ ]:
a[-5:-1:-1]

array([], dtype=int64)

In [ ]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1[[ True,  True,  True,  True,  True, False, False, False, False,
       False]]

array([1, 2, 3, 4, 5])

In [ ]:
m1[m1 < 6]

array([1, 2, 3, 4, 5])

In [ ]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m1[m1%2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]
#a[2:] = [6,7,8]

In [ ]:
a

[1, 2, 6, 7, 8]

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]


In [ ]:
a

[1, 2, 3, 6, 8]

In [ ]:
a[::-1]

[8, 6, 3, 2, 1]

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK


Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 8.61MB/s]


In [ ]:
score = np.loadtxt('survey.txt', dtype ='int')


In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
score.ndim

1

In [ ]:
score.shape

(1167,)

NPS = % Promoters - % Detractors


In [ ]:
100 -> 20 -> 20/100

In [ ]:
detractor = score[score <= 6]

In [ ]:
len(detractor)

332

In [ ]:
percentage_det = len(detractor)/len(score) * 100

In [ ]:
percentage_det

28.449014567266495

In [ ]:
detractor.shape[0]

332

In [ ]:
332/1167

0.28449014567266495

In [ ]:
promotor = score[score >=9]

In [ ]:
len(promotor)

609

In [ ]:
609/1167

0.5218508997429306

In [ ]:
52 - 28

24

In [ ]:
100 -> 0 80 20